@startuml
!include <C4/C4_Component>

LAYOUT_WITH_LEGEND()

Container(ui, "User Interface", "libcosmic", "Provides a graphical user interface")


Container_Boundary(java, "ha backend") {
  Component(api, "ApiController", "Rest Controller", "Allows to view and create simulations")
  Component(simulation, "Simulation", "Class", "Can run simulations")
  Component(logger, "Logger", "Class", "Writes out simulation logs")
  Rel_L(api, simulation, "Uses")
  Rel_L(simulation, logger, "Uses")
}

Rel_L(ui, api, "Uses", "JSON/HTTP")

@enduml
